# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: python

os: linux

python:
    - "2.7"
    # - "3.5"

before_install:
    - pwd
    - ls /usr/lib/
    - mkdir -p ${HOME}/bin
    - mkdir -p ${HOME}/lib
    - mkdir -p ${HOME}/code

# command to install dependencies
install:
    - pip install -e .
    - pip install -r requirements.txt

  # UCSC Tools
    - cd ${HOME}/lib
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/bedToBigBed
    - wget http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig

before_script:
    - cd ${HOME}/bin

    - ln -s ${HOME}/lib/bedToBigBed bedToBigBed
    - ln -s ${HOME}/lib/wigToBigWig wigToBigWig

    - export PATH="$PWD:$PATH"

    - cd ${HOME}/build/Multiscale-Genomics/mg-dm-api

# command to run tests
script:
    pytest -m "not underdeverlopment"
