language: python

os: linux
dist: trusty
group: edge

python:
  - "2.7"
  #- "3.5"

# command to install dependencies
install:
  - pip install -e .
  - pip install -r requirements.txt

before_script:
  - pwd

# command to run tests
script: pytest -m "not underdeverlopment"
